apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: redis-chart
  namespace: argocd
spec:
  project: default
  source:
    repoURL: git@bitbucket.org:prevoirsolutionsinformatiques/gitops.git
    targetRevision: HEAD
    path: charts/redis
    helm:
      valueFiles: 
      - values-production.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: redis
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true