apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kubernetes-external-secret
  namespace: argocd
spec:
  destination:
    namespace: kube-system
    server: https://kubernetes.default.svc
  project: default
  source:
    chart: kubernetes-external-secrets 
    repoURL: https://external-secrets.github.io/kubernetes-external-secrets/
    targetRevision: 6.4.0
    helm:
      parameters:
      - name: serviceAccount.name
        value: svc-gke-kubernetes-external-secret-dev # created from terraform
      - name: serviceAccount.create
        value: "false"
      - name: env.POLLER_INTERVAL_MILLISECONDS
        value: "600000" # Every 10 minutes. GCP charges for pulling secrets
      - name: fullnameOverride
        value: "external-secret" # Every 10 minutes. GCP charges for pulling secrets
