apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: linkerd-staging
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://gitlab.com/deimosdev/client-project/optty/infrastructure/gitops.git
    targetRevision: HEAD
    path: staging/linkerd
  destination:
    server: https://kubernetes.default.svc
    namespace: linkerd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
