apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "optty.fullname" . }}
  labels:
    {{- include "optty.labels" . | nindent 4 }}
  namespace: {{ .Release.Namespace }}
  annotations:
    {{- include "optty.deployment.annotations" . | nindent 4 }}
spec:
{{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
{{- end }}
  selector:
    matchLabels:
      {{- include "optty.selectorLabels" . | nindent 6 }}
  template:
    metadata:
    {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      labels:
        {{- include "optty.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "optty.serviceAccountName" . }}
      automountServiceAccountToken: {{ .Values.automountServiceAccountToken }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ include "optty.fullname" . }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.name }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          {{- with .Values.env}}
          env: 
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- if .Values.envFromExternalSecret }}
          envFrom:
          - secretRef:
            name: {{ include "optty.fullname" . }}
          {{- end }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.targetPort }}
              protocol: TCP
          {{- with .Values.probes.livenessProbe }}
          livenessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.probes.readinessProbe }}
          readinessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- if .Values.sidecar.enabled }}  
        - name: {{ .Values.sidecar.name }}
          image: "{{ .Values.sidecar.image.repository }}:{{ .Values.sidecar.image.tag }}"
          imagePullPolicy: {{ .Values.sidecar.image.pullPolicy }}
          args:
            {{- range .Values.sidecar.args }}
            - {{ . | quote }}
            {{- end }}
          ports:
            - name: sidecar
              containerPort: {{ .Values.sidecar.port }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: {{ .Values.sidecar.probe.path }}
              port: sidecar
        {{- if .Values.sidecar.probe.httpHeaders.enabled }}
              httpHeaders:
              - name: {{ .Values.sidecar.probe.httpHeaders.liveness.name }}
                value: {{ .Values.sidecar.probe.httpHeaders.liveness.value }}
        {{- end }}
            initialDelaySeconds: {{ .Values.sidecar.probe.initialDelaySeconds }}
            periodSeconds: {{ .Values.sidecar.probe.periodSeconds }}
          readinessProbe:
            httpGet:
              path: {{ .Values.sidecar.probe.path }}
              port: sidecar
        {{- if .Values.sidecar.probe.httpHeaders.enabled }}
              httpHeaders:
              - name: {{ .Values.sidecar.probe.httpHeaders.readiness.name }}
                value: {{ .Values.sidecar.probe.httpHeaders.readiness.value }}
        {{- end }}
            initialDelaySeconds: {{ .Values.sidecar.probe.initialDelaySeconds }}
            periodSeconds: {{ .Values.sidecar.probe.periodSeconds }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}