apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://bitbucket.org/prevoirsolutionsinformatiques/infrastructure-as-code/src/master/gitops/
    targetRevision: HEAD
    path: dev/cert-manager
  destination:
    server: https://kubernetes.default.svc
    namespace: cert-manager
  syncPolicy:
    automated:
      prune: false
      selfHeal: false
    syncOptions:
      - Validate=false
      - CreateNamespace=true
