apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rook-operator-chart
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  destination:
    namespace: rook-ceph
    server: https://kubernetes.default.svc
  project: default
  source:
    chart: rook-ceph 
    repoURL: https://charts.rook.io/release
    targetRevision: 1.7.0