#-------------------------------------
# Resource Quotas for common namespace
#-------------------------------------
# Memory and CPU Quotas

apiVersion: v1
kind: ResourceQuota
metadata:
  name: memory-cpu-quota
  namespace: common
spec:
  hard:
    requests.cpu: "1"
    requests.memory: 1Gi
    limits.cpu: "2"
    limits.memory: 2Gi

---
#-------------------------------------------
# Resource Quotas for data-mongodb namespace
#-------------------------------------------
# Memory and CPU Quotas

apiVersion: v1
kind: ResourceQuota
metadata:
  name: memory-cpu-quota
  namespace: data-mongodb
spec:
  hard:
    requests.cpu: "1"
    requests.memory: 1Gi
    limits.cpu: "2"
    limits.memory: 2Gi

---
#--------------------------------------
# Resource Quotas for insight namespace
#--------------------------------------
# Memory and CPU Quotas

apiVersion: v1
kind: ResourceQuota
metadata:
  name: memory-cpu-quota
  namespace: insight
spec:
  hard:
    requests.cpu: "1"
    requests.memory: 1Gi
    limits.cpu: "2"
    limits.memory: 2Gi