---
- name: Install Docker
  hosts: all
  #remote_user: root

  tasks:
    - name: Ubuntu | Install Docker
      apt:
        name: docker.io
        state: present

    - name: Ubuntu | Start and enable docker service
      service:
        name: docker
        state: started
        enabled: yes

    - name: Ubuntu | Add user(s) to "docker" group
      user:
        name: "riaan"
        groups: "docker"
        append: true

    - name: Ubuntu | net.bridge.bridge-nf-call-iptables
      ansible.posix.sysctl:
        name: net.bridge.bridge-nf-call-iptables
        value: "1"
        state: present

    - name: Unconditionally reboot the machine with all defaults
      reboot:
        reboot_timeout: 3


# ---
# - name: "RUN rke up"
#   command: "{{ rke_cluster_bin }} up --config {{ rke_cluster_config }}"
#   register: rke_up_result
#   changed_when: false

# - name: "rke up Result"
#   debug:
#     msg: "{{ rke_up_result.stdout }}"
#   when: rke_up_result is not skipped

# - name: Check that KubeConfig exists
#   stat:
#     path: "{{ rke_cluster_kube_config }}"
#   register: kubeconfig_result