apiVersion: v1
kind: Secret
metadata:
  name: linkerd-trust-anchor
  namespace: linkerd
type: kubernetes.io/tls
data:
  tls.crt: |
        -----BEGIN CERTIFICATE-----
        MIIBjjCCATSgAwIBAgIRALv0txmRL8v+II3RLMTJqEIwCgYIKoZIzj0EAwIwJTEj
        MCEGA1UEAxMacm9vdC5saW5rZXJkLmNsdXN0ZXIubG9jYWwwHhcNMjEwODA0MTcy
        NTQxWhcNMjYwODAzMTcyNTQxWjAlMSMwIQYDVQQDExpyb290LmxpbmtlcmQuY2x1
        c3Rlci5sb2NhbDBZMBMGByqGSM49AgEGCCqGSM49AwEHA0IABGxjb92IHe/cpecK
        lb1O1Xvhhgl5C1v0fBkLoL9pH3R2PucNgVKypSWrJhGR/paE9tmPOckLqVWcvIN4
        QVsVd3yjRTBDMA4GA1UdDwEB/wQEAwIBBjASBgNVHRMBAf8ECDAGAQH/AgEBMB0G
        A1UdDgQWBBQQiWVEtldDBWiF+zl6VzrlxMsWXzAKBggqhkjOPQQDAgNIADBFAiAK
        QqzARq0jhZqsa5tfj9yyxp049tLRhVOyzXqPaILiZgIhALm+GdI2uplPL8xjN56l
        pHTJYTVqOiUCOCD1vC8fRvFL
        -----END CERTIFICATE-----
  tls.key: |
        -----BEGIN EC PRIVATE KEY-----
        MHcCAQEEINjD5gnN+EHvCrmOOO98cUnNAnpigSOZ4mi1Y8MJnnSRoAoGCCqGSM49
        AwEHoUQDQgAEbGNv3Ygd79yl5wqVvU7Ve+GGCXkLW/R8GQugv2kfdHY+5w2BUrKl
        JasmEZH+loT22Y85yQupVZy8g3hBWxV3fA==
        -----END EC PRIVATE KEY-----

---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: linkerd-trust-anchor
  namespace: linkerd
spec:
  encryptedData:
    tls.crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUJqakNDQVRTZ0F3SUJBZ0lSQUx2MHR4bVJMOHYrSUkzUkxNVEpxRUl3Q2dZSUtvWkl6ajBFQXdJd0pURWoKTUNFR0ExVUVBeE1hY205dmRDNXNhVzVyWlhKa0xtTnNkWE4wWlhJdWJHOWpZV3d3SGhjTk1qRXdPREEwTVRjeQpOVFF4V2hjTk1qWXdPREF6TVRjeU5UUXhXakFsTVNNd0lRWURWUVFERXhweWIyOTBMbXhwYm10bGNtUXVZMngxCmMzUmxjaTVzYjJOaGJEQlpNQk1HQnlxR1NNNDlBZ0VHQ0NxR1NNNDlBd0VIQTBJQUJHeGpiOTJJSGUvY3BlY0sKbGIxTzFYdmhoZ2w1QzF2MGZCa0xvTDlwSDNSMlB1Y05nVkt5cFNXckpoR1IvcGFFOXRtUE9ja0xxVldjdklONApRVnNWZDN5alJUQkRNQTRHQTFVZER3RUIvd1FFQXdJQkJqQVNCZ05WSFJNQkFmOEVDREFHQVFIL0FnRUJNQjBHCkExVWREZ1FXQkJRUWlXVkV0bGREQldpRit6bDZWenJseE1zV1h6QUtCZ2dxaGtqT1BRUURBZ05JQURCRkFpQUsKUXF6QVJxMGpoWnFzYTV0Zmo5eXl4cDA0OXRMUmhWT3l6WHFQYUlMaVpnSWhBTG0rR2RJMnVwbFBMOHhqTjU2bApwSFRKWVRWcU9pVUNPQ0QxdkM4ZlJ2RkwKLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQ==
    tls.key: LS0tLS1CRUdJTiBFQyBQUklWQVRFIEtFWS0tLS0tCk1IY0NBUUVFSU5qRDVnbk4rRUh2Q3JtT09POThjVW5OQW5waWdTT1o0bWkxWThNSm5uU1JvQW9HQ0NxR1NNNDkKQXdFSG9VUURRZ0FFYkdOdjNZZ2Q3OXlsNXdxVnZVN1ZlK0dHQ1hrTFcvUjhHUXVndjJrZmRIWSs1dzJCVXJLbApKYXNtRVpIK2xvVDIyWTg1eVF1cFZaeThnM2hCV3hWM2ZBPT0KLS0tLS1FTkQgRUMgUFJJVkFURSBLRVktLS0tLQ==
  template:
    metadata:
      annotations:
        linkerd.io/created-by: linkerd/cli stable-2.9.0
        linkerd.io/identity-issuer-expiry: "2021-12-09T13:11:01Z"
      creationTimestamp: null
      labels:
        linkerd.io/control-plane-component: identity
        linkerd.io/control-plane-ns: linkerd
      name: linkerd-trust-anchor
      namespace: linkerd
    type: kubernetes.io/tls

---

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vault-chart
  namespace: argocd
spec:
  project: default
  source:
    repoURL: git@bitbucket.org:prevoirsolutionsinformatiques/gitops.git
    targetRevision: HEAD
    path: charts/vault
    helm:
      values: |
        replicas: 3
        server:
          ingress:
            enabled: true
            annotations:
              kubernetes.io/ingress.class: nginx
              kubernetes.io/tls-acme: "true"
              cert-manager.io/cluster-issuer: lets-encrypt-nginx
            hosts:
              - host: vault.prevoir.com
                paths: []
            tls: 
              - secretName: vault-tls
                hosts:
                  - vault.prevoir.com
  destination:
    server: https://kubernetes.default.svc
    namespace: data-vault
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true