apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: {{ include "hello-kubernetes.name" . }}
  annotations:
    # use the shared ingress-nginx
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
    - host: myservicea.foo.org
      http:
        paths:
          - path: /
            backend:
              serviceName: {{ include "hello-kubernetes.name" . }}
              servicePort: 80