apiVersion: v1
kind: ServiceAccount
automountServiceAccountToken: true
metadata:
  name: vault-auth
  namespace: data-vault
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
   name: role-tokenreview-binding
   namespace: data-vault
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:auth-delegator
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: ServiceAccount
  name: vault-auth
  namespace: data-vault
