apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nats-operator
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://gitlab.com/deimosdev/client-project/optty/infrastructure/gitops.git
    targetRevision: HEAD
    path: charts/nats-operator-chart
    helm:
      values: |
        fullnameOverride: "nats-operator"
        clusterScoped: false
        cluster:
          namespace: apps
          name: nats
          size: 1
          version: 2.1.8
          annotations:
            argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
          auth:
            enabled: true
            enableServiceAccounts: true
          configReload:
            enabled: true
  destination:
    server: https://kubernetes.default.svc
    namespace: apps
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
