apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dev-namespaces
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://niyez@bitbucket.org/prevoirsolutionsinformatiques/infrastructure-as-code.git
    targetRevision: HEAD
    path: gitops/dev/namespaces
  destination:
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: false
      selfHeal: false
    syncOptions:
      - Validate=false
      - CreateNamespace=true
