apiVersion: v1
kind: Secret
metadata:
  name: tls-secret
  namespace: hello-web-app
spec:
  secretName: tls-secret
  driver: azure
  secretReference:    
    - key: tls.crt
      name: "neyo-test-ca"
    - key: tls.key
      name: "neyo-test-ca"
