apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mongodb-chart
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://niyez@bitbucket.org/prevoirsolutionsinformatiques/infrastructure-as-code.git
    targetRevision: HEAD
    path: gitops/charts/mongodb
    helm:
      values: |
        replicas: 3
  destination:
    server: https://kubernetes.default.svc
    namespace: data-mongodb
  syncPolicy:
    automated:
      prune: false
      selfHeal: false
    syncOptions:
      - Validate=false
      - CreateNamespace=true