apiVersion: v1
kind: Secret
metadata:
  name: grafana-agent-secret
  namespace: monitoring
data:
  grafana-k8s-cluster-name: [todo - clustername to show in grafana]
  grafana-loki-url: https://logs-prod-eu-west-0.grafana.net/api/prom/push
  grafana-loki-password: [todo]
  grafana-loki-username: [todo]
  grafana-prom-url: https://prometheus-prod-01-eu-west-0.grafana.net/api/prom/push
  grafana-prom-password: [todo]
  grafana-prom-username: [todo]
  grafana-temp-url: tempo-eu-west-0.grafana.net:443
  grafana-temp-password: [todo]
  grafana-temp-username: [todo]