apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kubernetes-external-secret
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  destination:
    namespace: kube-system
    server: https://kubernetes.default.svc
  project: default
  source:
    chart: kubernetes-external-secrets 
    repoURL: https://external-secrets.github.io/kubernetes-external-secrets/
    targetRevision: 8.3.0
    helm:
      values: |
        env:
          VAULT_ADDR: http://vault-chart:8200  #change to vault url
          DEFAULT_VAULT_MOUNT_POINT: "auth/kubernetes/config" # optional, default value to be used if not specified in the ExternalSecret
          DEFAULT_VAULT_ROLE: "diy-linkerd" #optional, default value to be used if not specified in the ExternalSecret
