all:
  hosts:
    k8-master01.local.lab:
      ansible_host: 10.168.1.111
      ip: 10.168.1.111
      access_ip: 10.168.1.111
    k8-master02.local.lab:
      ansible_host: 10.168.1.112
      ip: 10.168.1.112
      access_ip: 10.168.1.112
    k8-master03.local.lab:
      ansible_host: 10.168.1.113
      ip: 10.168.1.113
      access_ip: 10.168.1.113
    k8-worker01.local.lab:
      ansible_host: 10.168.1.114
      ip: 10.168.1.114
      access_ip: 10.168.1.114
    k8-worker02.local.lab:
      ansible_host: 10.168.1.115
      ip: 10.168.1.115
      access_ip: 10.168.1.115
    k8-worker03.local.lab:
      ansible_host: 10.168.1.116
      ip: 10.168.1.116
      access_ip: 10.168.1.116

  children:
    kube_control_plane:
      hosts:
        k8-master01.local.lab:
        k8-master02.local.lab:
        k8-master03.local.lab:
    kube_node:
      hosts:
        k8-worker01.local.lab:
        k8-worker02.local.lab:
        k8-worker03.local.lab:

    etcd:
      hosts:
        k8-worker01.local.lab:
        k8-worker02.local.lab:
        k8-worker03.local.lab:
    k8s_cluster:
      children:
        kube_control_plane:
        kube_node:
    calico_rr:
      hosts: {}
