apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: falco-exporter
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://falcosecurity.github.io/charts
    chart: falco-exporter
    targetRevision: 0.4.1
    helm:
      parameters:
      - name: grafanaDashboard.enabled
        value: "true"
  destination:
    server: https://kubernetes.default.svc
    namespace: falco
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
