apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dev-rbac
  namespace: argocd
spec:
  project: default
  source:
    repoURL: git@bitbucket.org:prevoirsolutionsinformatiques/gitops.git
    targetRevision: HEAD
    path: k8sDiyGCP/rbac
  destination:
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
