apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: linkerd-helm
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://helm.linkerd.io/stable
    chart: linkerd2
    helm:
      parameters:
      - name: identity.issuer.scheme
        value: kubernetes.io/tls
      - name: installNamespace
        value: "false"
      - name: global.identityTrustAnchorsPEM
        value: |
          -----BEGIN CERTIFICATE-----
          MIIBlTCCATygAwIBAgIRAO6iw5fwBF9dMDTtmVGoOw0wCgYIKoZIzj0EAwIwKTEn
          MCUGA1UEAxMeaWRlbnRpdHkubGlua2VyZC5jbHVzdGVyLmxvY2FsMB4XDTIwMTIw
          OTEzMjMyMVoXDTMwMTIwNzEzMjMyMVowKTEnMCUGA1UEAxMeaWRlbnRpdHkubGlu
          a2VyZC5jbHVzdGVyLmxvY2FsMFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEwohZ
          aCe2jsrsyA5JA9/C1tTwrme9xMgBSSatPaG0cF25bwU9jp8c6yIl9MRcU8zoh8eQ
          jxglOQMkBt9ndbrqyKNFMEMwDgYDVR0PAQH/BAQDAgEGMBIGA1UdEwEB/wQIMAYB
          Af8CAQEwHQYDVR0OBBYEFNsav1i1eqXN05cfbqJ7mW5D84zXMAoGCCqGSM49BAMC
          A0cAMEQCIE2wm9Nbf4FmBp9PGEES6XnpN9Fi/QZ7pgcugXXE6YVvAiAapo3I7yFy
          1Iq4nZy9H0xoaAX/VxWcSSIbxWbNrIEd1g==
          -----END CERTIFICATE-----
    targetRevision: 2.9.0
  destination:
    server: https://kubernetes.default.svc
    namespace: linkerd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
