#------------------------------
# TERRAFORM INIT
#------------------------------
init-staging:
  extends: .init
  variables:
    CREDENTIALS: $GOOGLE_APPLICATION_CREDENTIALS_STAGING
    DEPLOY_DIR: staging
  environment:
    name: staging
    action: prepare

#------------------------------
# TERRAFORM LINT
#------------------------------
validate-staging:
  extends: .validate
  variables:
    CREDENTIALS: $GOOGLE_APPLICATION_CREDENTIALS_STAGING
    DEPLOY_DIR: staging
  needs:
    - init-staging
  environment:
    name: staging
    action: prepare

#------------------------------
# TERRAFORM PLAN
#------------------------------
plan-staging:
  extends: .plan
  variables:
    CREDENTIALS: $GOOGLE_APPLICATION_CREDENTIALS_STAGING
    DEPLOY_DIR: staging
  needs:
    - lint
    - validate-staging
  environment:
    name: staging
    action: prepare

#------------------------------
# TERRAFORM APPLY
#------------------------------
apply-staging:
  extends: .apply
  variables:
    CREDENTIALS: $GOOGLE_APPLICATION_CREDENTIALS_STAGING
    DEPLOY_DIR: staging
  needs:
    - job: plan-staging
      artifacts: true
  environment:
    name: staging
