apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
   name: minio-object-storage
# Change "rook-ceph" provisioner prefix to match the operator namespace if needed
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer
reclaimPolicy: Delete

