apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: minio-chart
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  destination:
    namespace: minio-operator
    server: https://kubernetes.default.svc
  project: default
  source:
    chart: minio-operator 
    repoURL: https://operator.min.io/
    targetRevision: 4.2.2