apiVersion: "kubernetes-client.io/v1"
kind: ExternalSecret
metadata:
  name: linkerd-trust-anchor
  namespace: linkerd
spec:
  backendType: vault
  # Your authentication mount point, e.g. "kubernetes"
  # Overrides cluster DEFAULT_VAULT_MOUNT_POINT
  #vaultMountPoint: auth/kubernetes/config
  # The vault role that will be used to fetch the secrets
  # This role will need to be bound to kubernetes-external-secret's ServiceAccount; see Vault's documentation:
  # https://www.vaultproject.io/docs/auth/kubernetes.html
  # Overrides cluster DEFAULT_VAULT_ROLE
  #vaultRole: linkerd
  data:
    - name: diy-tls-crt
      # The full path of the secret to read, as in `vault read secret/data/hello-service/credentials`
      key: secret/linkerd/diy-trustanchor
      property: diy-ca.crt
    # Vault values are matched individually. If you have several keys in your Vault secret, you will need to add them all separately
    - name: diy-tls-key
      key: secret/linkerd/diy-trustanchor
      property: diy-ca.key
