apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloudflare-api-token-secret
  namespace: cert-manager
spec:
  encryptedData:
    api-token: AgDQTX4vSc/47UbXJGMIOKbvT/Bf28Exmi+XsW42Fw1TkeDxBwmJ7uc1fCFNeOy2UVYTndQXbnm8zi16U+jKFKdHWlhcn8SrTZcHQwDfCk28S5Zg6QVf4ThfE8wljF2UQzbL/JQpnbsl9AszK9CHg+dSQ98zbnnBCrYXCPpmNIfPUUtzLTAS6h/MFofsae1UYwc0ItSTEOGbB6HJylzwvR/LbN4H1etYnxWuXPqvQErIjVEQnm3EYI3mQt7AyrHDzNvMuXYx+yIJm0uFwArQImEgt6ZtXKWECp2je5T0cVgcJu6Iais79poUPLOoPNaCf6pBOfPIHEmM9LM4lLbtoPCsOy8Y5IyBEIwXeYOnuLNX6HFWGF4OVQXvYF8Dur/T5nES5Cbkql4cnYp0/3h+fyj+W3adwy+rBikERN3j4R/UJSwVmpIviSlDZxssUePJA1tVta/rpBBPsfY4zgo/XCF1TRYk5zTRKhYuVB3CNX7F9/LJdYS6wWZjipxxtqlCQRFryroV/yZfmiAwwnkeLAzGcrNeL4loJ5p9kVBqUmahDAUIwZeOO9fSHeMb4XmnqQqZjMBTkuDTZ84oJkjkbNHCiYcwPeLX5vcznPQgAsQ0uT5kcQOY8Yz4Ob0B7ReT2oqIAuCGSTth6+ttUlRZeGqaPtytvR68QUgtnRjvm5zInP4o9R3f6B6BCm7T+V/5kQG6FND09bUTPiZnrP5lKX7QStPABJHv9XbmgZhm1cFOVZ7/WDWNWGOV
  template:
    metadata:
      creationTimestamp: null
      name: cloudflare-api-token-secret
      namespace: cert-manager
    type: Opaque

