## Kubernetes Manifest File to Create all Pre-Defined NameSpaces
kind: Namespace
apiVersion: v1
metadata:
  name: common
  labels:
    name: common
---
kind: Namespace
apiVersion: v1
metadata:
  name: insight
  labels:
    name: insight
---
kind: Namespace
apiVersion: v1
metadata:
  name: data
  labels:
    name: data
---
kind: Namespace
apiVersion: v1
metadata:
  name: web
  labels:
    name: web