#------------------------------
# TERRAFORM INIT
#------------------------------
init-dev:
  extends: .init
  variables:
    CREDENTIALS: $GOOGLE_APPLICATION_CREDENTIALS_DEV
    DEPLOY_DIR: dev
  environment:
    name: dev
    action: prepare

#------------------------------
# TERRAFORM LINT
#------------------------------
validate-dev:
  extends: .validate
  variables:
    CREDENTIALS: $GOOGLE_APPLICATION_CREDENTIALS_DEV
    DEPLOY_DIR: dev
  needs:
    - init-dev
  environment:
    name: dev
    action: prepare

#------------------------------
# TERRAFORM PLAN
#------------------------------
plan-dev:
  extends: .plan
  variables:
    CREDENTIALS: $GOOGLE_APPLICATION_CREDENTIALS_DEV
    DEPLOY_DIR: dev
  needs:
    - lint
    - validate-dev
  environment:
    name: dev
    action: prepare

#------------------------------
# TERRAFORM APPLY
#------------------------------
apply-dev:
  extends: .apply
  variables:
    CREDENTIALS: $GOOGLE_APPLICATION_CREDENTIALS_DEV
    DEPLOY_DIR: dev
  needs:
    - job: plan-dev
      artifacts: true
  environment:
    name: dev
