---
#Daemonset.yaml
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: promtail-daemonset
spec:
  selector:
    matchLabels:
      name: promtail
  template:
    metadata:
      labels:
        name: promtail
    spec:
      serviceAccount: SERVICE_ACCOUNT
      serviceAccountName: SERVICE_ACCOUNT
      volumes:
      - name: logs
        hostPath:
          path: HOST_PATH
      - name: promtail-config
        configMap:
          name: promtail-configmap
      containers:
      - name: promtail-container
        image: grafana/promtail
        args:
        - -config.file=/etc/promtail/promtail.yaml
        volumeMounts:
        - name: logs
          mountPath: MOUNT_PATH
        - name: promtail-config
          mountPath: /etc/promtail

---
#configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: promtail-config
  namespace: loki
data:
  promtail.yaml: |
    server:
      http_listen_port: 9080
      grpc_listen_port: 0

    client_config
      url: http://ip_or_hostname_where_loki_runns:3100/loki/api/v1/push
      batchwait: 1s
      batchsize: 102400
    basic_auth:
      username:
      password:

    position_config
      filename: "/var/log/positions.yaml"
      sync_period: 10s
    
    scrape_config:
    - job_name: my-container-log
      static_configs:
        - targets:
            - localhost
          labels:
            job: containerlogs
            host: localshost
            __path__: /var/lib/docker/containers/*/*log

    - job_name: rook-ceph-pods
      pipeline_stages:
        - docker: {}
      kubernetes_sd_configs:
        - role: pod
      relabel_configs:
        - source_labels: [__meta_kubernetes_namespace]
          action: drop
          regex: .+
        - action: keep
          regex: ambassador
          source_labels:
            - __meta_kubernetes_namespace
            - __meta_kubernetes_pod_namespace
    - job_name: kubernetes-pods-app
      pipeline_stages:
        - docker: {}
      kubernetes_sd_configs:
        - role: pod
      relabel_configs:
        - source_labels: [__meta_kubernetes_namespace]
          action: drop
          regex: .+
        - action: keep
          regex: ambassador
          source_labels:
            - __meta_kubernetes_namespace
            - __meta_kubernetes_pod_namespace
  
    - job_name: kubernetes-pods-direct-controllers
      pipeline_stages:
        - docker: {}
      kubernetes_sd_configs:
        - role: pod
      relabel_configs:
        - source_labels: [__meta_kubernetes_namespace]
          action: drop
          regex: .+
        - action: keep
          regex: ambassador
          source_labels:
            - __meta_kubernetes_namespace
            - __meta_kubernetes_pod_namespace

    - job_name: kubernetes-pods-indirect-controller
      pipeline_stages:
        - docker: {}
      kubernetes_sd_configs:
        - role: pod
      relabel_configs:
        - source_labels: [__meta_kubernetes_namespace]
          action: drop
          regex: .+
        - action: keep
          regex: ambassador
          source_labels:
            - __meta_kubernetes_namespace
            - __meta_kubernetes_pod_namespace

    - job_name: kubernetes-pods-static
      pipeline_stages:
        - docker: {}
      kubernetes_sd_configs:
        - role: pod
      relabel_configs:
        - source_labels: [__meta_kubernetes_namespace]
          action: drop
          regex: .+
        - action: keep
          regex: ambassador
          source_labels:
            - __meta_kubernetes_namespace
            - __meta_kubernetes_pod_namespace

  

---
#Clusterrole.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: promtail-clusterrole
rules:
  - apiGroups: [""]
    resources:
    - nodes
    - services
    - pods
    verbs:
    - get
    - watch
    - list

---
#ServiceAccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: promtail-serviceaccount

---
#Rolebinding.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: promtail-clusterrolebinding
subjects:
    - kind: ServiceAccount
      name: promtail-serviceaccount
      namespace: default
roleRef:
    kind: ClusterRole
    name: promtail-clusterrole
    apiGroup: rbac.authorization.k8s.io

