apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-ingress-controller
  namespace: argocd
spec:
  project: default
  source:
    repoURL: git@bitbucket.org:prevoirsolutionsinformatiques/gitops.git
    targetRevision: HEAD
    path: baremetal/nginx-controller
  destination:
    server: https://kubernetes.default.svc
    namespace: nginx-ingress
  syncPolicy:
    automated:
      prune: true #delete resources made to repo
      selfHeal: true #reset modification made to cluster
    syncOptions:
      - CreateNamespace=true
