variables:
  CLI_VERSION: latest

unit_test:karma:
  stage: build
  image: trion/ng-cli-karma
  allow_failure: false
  script:
    - npm i
    - ng test --code-coverage --progress false --watch false
  coverage: '/Lines \W+: (\d+\.\d+)%.*/'
  artifacts:
    paths:
      - coverage/
  tags:
    - docker

test:nglint:
  stage: build
  image: trion/ng-cli:${CLI_VERSION}
  script:
  - npm i
  - ng lint
  tags:
  - docker
