resources:
  - https://github.com/jetstack/cert-manager/releases/download/v1.0.4/cert-manager.yaml
  - lets-encrypt-issuer.yaml
  - self-signed-issuer.yaml
  - lets-encrypt-issuer-gce.yaml

patchesStrategicMerge:
- overlay.yaml
